from django.test import TestCase

# Create your tests here.
{
    'role_list': {'id': 1, 'title': '角色名单', 'url': '/rbac/role/list/', 'pid': 1, 'p_title': '角色名单', 'p_url': '/rbac/role/list/'},
    'customer_list': {'id': 23, 'title': '消费者列表', 'url': '/customer/list/', 'pid': 23, 'p_title': '消费者列表', 'p_url': '/customer/list/'},
    'payment_list': {'id': 29, 'title': '支付列表', 'url': '/payment/list/', 'pid': 29, 'p_title': '支付列表', 'p_url': '/payment/list/'},
    'menu_list': {'id': 10, 'title': '菜单列表', 'url': '/rbac/menu/list/', 'pid': 10, 'p_title': '菜单列表', 'p_url': '/rbac/menu/list/'},
    'distribute_permissions': {'id': 22, 'title': '分配权限', 'url': '/rbac/distribute/permissions/', 'pid': 22, 'p_title': '分配权限', 'p_url': '/rbac/distribute/permissions/'},
    'role_add': {'id': 2, 'title': '角色添加', 'url': '/rbac/role/add/', 'pid': 1, 'p_title': '角色名单', 'p_url': '/rbac/role/list/'},
    'role_edit': {'id': 3, 'title': '角色编辑', 'url': '/rbac/role/edit/(?P<pk>\\d+)/', 'pid': 1, 'p_title': '角色名单', 'p_url': '/rbac/role/list/'},
    'role_del': {'id': 4, 'title': '角色删除', 'url': '/rbac/role/del/(?P<pk>\\d+)/', 'pid': 1, 'p_title': '角色名单', 'p_url': '/rbac/role/list/'},
    'user_list': {'id': 5, 'title': '用户列表', 'url': '/rbac/user/list/', 'pid': 1, 'p_title': '角色名单', 'p_url': '/rbac/role/list/'},
    'user_add': {'id': 6, 'title': '用户添加', 'url': '/rbac/user/add/', 'pid': 1, 'p_title': '角色名单', 'p_url': '/rbac/role/list/'},
    'user_edit': {'id': 7, 'title': '用户编辑', 'url': '/rbac/user/edit/(?P<pk>\\d+)/', 'pid': 1, 'p_title': '角色名单', 'p_url': '/rbac/role/list/'},
    'user_del': {'id': 8, 'title': '用户删除', 'url': '/rbac/user/del/(?P<pk>\\d+)/', 'pid': 1, 'p_title': '角色名单', 'p_url': '/rbac/role/list/'},
    'user_reset_password': {'id': 9, 'title': '重置密码', 'url': '/rbac/user/reset/password/(?P<pk>\\d+)/', 'pid': 1, 'p_title': '角色名单', 'p_url': '/rbac/role/list/'},
    'menu_add': {'id': 11, 'title': '菜单添加', 'url': '/rbac/menu/add/', 'pid': 10, 'p_title': '菜单列表', 'p_url': '/rbac/menu/list/'},
    'menu_edit': {'id': 12, 'title': '菜单编辑', 'url': '/rbac/menu/edit/(?P<pk>\\d+)/', 'pid': 10, 'p_title': '菜单列表', 'p_url': '/rbac/menu/list/'},
    'menu_del': {'id': 13, 'title': '菜单删除', 'url': '/rbac/menu/del/(?P<pk>\\d+)/', 'pid': 10, 'p_title': '菜单列表', 'p_url': '/rbac/menu/list/'},
    'second_menu_add': {'id': 14, 'title': '二级菜单添加', 'url': '/rbac/second/menu/add/(?P<menu_id>\\d+)', 'pid': 10, 'p_title': '菜单列表', 'p_url': '/rbac/menu/list/'},
    'second_menu_edit': {'id': 15, 'title': '二级菜单编辑', 'url': '/rbac/second/menu/edit/(?P<pk>\\d+)/', 'pid': 10, 'p_title': '菜单列表', 'p_url': '/rbac/menu/list/'},
    'second_menu_del': {'id': 16, 'title': '二级菜单删除', 'url': '/rbac/second/menu/del/(?P<pk>\\d+)/', 'pid': 10, 'p_title': '菜单列表', 'p_url': '/rbac/menu/list/'},
    'permissin_add': {'id': 17, 'title': '权限添加', 'url': '/rbac/permission/add/(?P<second_menu_id>\\d+)/', 'pid': 22, 'p_title': '分配权限', 'p_url': '/rbac/distribute/permissions/'},
    'permissin_edit': {'id': 18, 'title': '权限编辑', 'url': '/rbac/permission/edit/(?P<pk>\\d+)/', 'pid': 22, 'p_title': '分配权限', 'p_url': '/rbac/distribute/permissions/'},
    'permissin_del': {'id': 19, 'title': '权限删除', 'url': '/rbac/permission/del/(?P<pk>\\d+)/', 'pid': 22, 'p_title': '分配权限', 'p_url': '/rbac/distribute/permissions/'},
    'multi_permissins': {'id': 20, 'title': '多级权限', 'url': '/rbac/multi/permissions/', 'pid': 22, 'p_title': '分配权限', 'p_url': '/rbac/distribute/permissions/'},
    'multi_permissins_del': {'id': 21, 'title': '多级权限删除', 'url': '/rbac/multi/permissions/del/(?P<pk>\\d+)/', 'pid': 22, 'p_title': '分配权限', 'p_url': '/rbac/distribute/permissions/'},
    'customer_add': {'id': 24, 'title': '消费者添加', 'url': '/customer/add/', 'pid': 23, 'p_title': '消费者列表', 'p_url': '/customer/list/'},
    'customer_edit': {'id': 25, 'title': '消费者编辑', 'url': '/customer/edit/(?P<cid>\\d+)/', 'pid': 23, 'p_title': '消费者列表', 'p_url': '/customer/list/'},
    'customer_del': {'id': 26, 'title': '消费者删除', 'url': '/customer/del/(?P<cid>\\d+)/', 'pid': 23, 'p_title': '消费者列表', 'p_url': '/customer/list/'},
    'customer_import': {'id': 27, 'title': '消费者导入', 'url': '/customer/import/', 'pid': 23, 'p_title': '消费者列表', 'p_url': '/customer/list/'},
    'customer_tpl': {'id': 28, 'title': '消费者tpl', 'url': '/customer/tpl/', 'pid': 23, 'p_title': '消费者列表', 'p_url': '/customer/list/'},
    'payment_add': {'id': 30, 'title': '支付添加', 'url': '/payment/add/', 'pid': 29, 'p_title': '支付列表', 'p_url': '/payment/list/'},
    'payment_edit': {'id': 31, 'title': '支付编辑', 'url': '/payment/edit/(?P<pid>\\d+)/', 'pid': 29, 'p_title': '支付列表', 'p_url': '/payment/list/'},
    'payment_del': {'id': 32, 'title': '支付删除', 'url': '/payment/del/(?P<pid>\\d+)/', 'pid': 29, 'p_title': '支付列表', 'p_url': '/payment/list/'}}
